### PR TITLE
Add additional TLS 1.3 cipher suites

### PR DESCRIPTION
**Pull request by jason-riddle**
I thought this was a solution to https://github.com/square/certigo/issues/202, but instead it attempts to solve the following issue when connect to a TLS 1.3 endpoint.

Notice that Cipher Suite has the value `UNKNOWN_1301`

```
certigo connect --verbose squareup.com:443
** TLS Connection **
Version: TLS 1.3
Cipher Suite: UNKNOWN_1301
```

However, after applying this fix the Cipher Suite section is empty

```
./certigo-with-tls13-ciphers connect --verbose squareup.com:443
** TLS Connection **
Version: TLS 1.3
Cipher Suite:
```

1301 maps to TLS_AES_128_GCM_SHA256 which I've already included in this PR

https://github.com/golang/go/blob/go1.13.1/src/crypto/tls/cipher_suites.go#L465

```
TLS_AES_128_GCM_SHA256       uint16 = 0x1301
```

I don't have time to look into this, so I'm marking this as WIP unless someone can offer a suggestion.

### CODE REVIEW

**Comment by captiosus** [comment]
This is because the new cipher suites do not contain "_WITH_" in the Slug name. The new cipher suites do not explicitly specify the key exchange algorithm. 

    func explainCipher(d description) description {
	    kexAndCipher := strings.Split(d.Slug, "_WITH_")
	    if len(kexAndCipher) == 2 {
            d.Name = fmt.Sprintf("%s key exchange, %s cipher", kexAndCipher[0][len("TLS_"):], kexAndCipher[1])
	    } else {
		d.Name = fmt.Sprintf("%s cipher", d.Slug[len("TLS_"):])
	    }
	    return d
    }

Above is a change for the **explainCipher** function that takes this into account

**Comment by jason-riddle** [comment]
Thanks @captiosus, I'll update my PR and verify the change.

**Comment by jason-riddle** [comment]
That change did work. new output looks like this for tls 1.3:

```
./certigo-with-tls13-ciphers connect --verbose squareup.com:443 | head -3
** TLS Connection **
Version: TLS 1.3
Cipher Suite: AES_128_GCM_SHA256 cipher
```

and tls <1.3 appears to be unchanged

```
./certigo-with-tls13-ciphers connect --verbose reddit.com:443 | head -3
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_RSA key exchange, AES_128_GCM_SHA256 cipher
```

**Comment by jason-riddle** [comment]
Removing WIP.

**Pull request merged**
