### PR TITLE
Smaller, more readable output

### PR DESCRIPTION
**Pull request by csstaub**
Changes:
* In non-verbose mode, only print CN (if present). If missing, fall back to everything.
* Makes output smaller but "compressing" the output lists for alternative DNS names and such, using `wrapWith` and `join` from Masterminds/sprig. Tries to use terminal width for output, with a default of 60 (should fit most terminals) and a max of 80 (otherwise it becomes unreadable).

New output:
```
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_ECDSA key exchange, AES_128_GCM_SHA256 cipher

** CERTIFICATE 1 **
Valid: 2017-03-01 14:47 UTC to 2017-05-24 14:22 UTC
Subject: CN=*.google.com
Issuer: CN=Google Internet Authority G2
Alternate DNS Names:
	*.google.com, *.android.com, *.appengine.google.com, *.cloud.google.com,
	*.gcp.gvt2.com, *.google-analytics.com, *.google.ca, *.google.cl,
	*.google.co.in, *.google.co.jp, *.google.co.uk, *.google.com.ar,
	*.google.com.au, *.google.com.br, *.google.com.co, *.google.com.mx,
	*.google.com.tr, *.google.com.vn, *.google.de, *.google.es, *.google.fr,
	*.google.hu, *.google.it, *.google.nl, *.google.pl, *.google.pt,
	*.googleadapis.com, *.googleapis.cn, *.googlecommerce.com,
	*.googlevideo.com, *.gstatic.cn, *.gstatic.com, *.gvt1.com, *.gvt2.com,
	*.metric.gstatic.com, *.urchin.com, *.url.google.com,
	*.youtube-nocookie.com, *.youtube.com, *.youtubeeducation.com,
	*.ytimg.com, android.clients.google.com, android.com,
	developer.android.google.cn, g.co, goo.gl, google-analytics.com,
	google.com, googlecommerce.com, urchin.com, www.goo.gl, youtu.be,
	youtube.com, youtubeeducation.com

** CERTIFICATE 2 **
Valid: 2015-04-01 00:00 UTC to 2017-12-31 23:59 UTC
Subject: CN=Google Internet Authority G2
Issuer: CN=GeoTrust Global CA

** CERTIFICATE 3 **
Valid: 2002-05-21 04:00 UTC to 2018-08-21 04:00 UTC
Subject: CN=GeoTrust Global CA
Issuer: C=US, O=Equifax, OU=Equifax Secure Certificate Authority
Warnings:
	Using SHA1-RSA, which is an outdated signature algorithm

Found 1 valid certificate chain(s):
[0] *.google.com
	=> Google Internet Authority G2
	=> GeoTrust Global CA [self-signed] [SHA1-RSA]
```

Old output:
```
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_ECDSA key exchange, AES_128_GCM_SHA256 cipher

** CERTIFICATE 1 **
Valid: 2017-03-01 14:47 UTC to 2017-05-24 14:22 UTC
Subject: C=US, ST=California, L=Mountain View, O=Google Inc, CN=*.google.com
Issuer: C=US, O=Google Inc, CN=Google Internet Authority G2
Alternate DNS Names:
	*.google.com
	*.android.com
	*.appengine.google.com
	*.cloud.google.com
	*.gcp.gvt2.com
	*.google-analytics.com
	*.google.ca
	*.google.cl
	*.google.co.in
	*.google.co.jp
	*.google.co.uk
	*.google.com.ar
	*.google.com.au
	*.google.com.br
	*.google.com.co
	*.google.com.mx
	*.google.com.tr
	*.google.com.vn
	*.google.de
	*.google.es
	*.google.fr
	*.google.hu
	*.google.it
	*.google.nl
	*.google.pl
	*.google.pt
	*.googleadapis.com
	*.googleapis.cn
	*.googlecommerce.com
	*.googlevideo.com
	*.gstatic.cn
	*.gstatic.com
	*.gvt1.com
	*.gvt2.com
	*.metric.gstatic.com
	*.urchin.com
	*.url.google.com
	*.youtube-nocookie.com
	*.youtube.com
	*.youtubeeducation.com
	*.ytimg.com
	android.clients.google.com
	android.com
	developer.android.google.cn
	g.co
	goo.gl
	google-analytics.com
	google.com
	googlecommerce.com
	urchin.com
	www.goo.gl
	youtu.be
	youtube.com
	youtubeeducation.com

** CERTIFICATE 2 **
Valid: 2015-04-01 00:00 UTC to 2017-12-31 23:59 UTC
Subject: C=US, O=Google Inc, CN=Google Internet Authority G2
Issuer: C=US, O=GeoTrust Inc., CN=GeoTrust Global CA

** CERTIFICATE 3 **
Valid: 2002-05-21 04:00 UTC to 2018-08-21 04:00 UTC
Subject: C=US, O=GeoTrust Inc., CN=GeoTrust Global CA
Issuer: C=US, O=Equifax, OU=Equifax Secure Certificate Authority
Warnings:
	Using SHA1-RSA, which is an outdated signature algorithm

Found 1 valid certificate chain(s):
[0] *.google.com
	=> Google Internet Authority G2
	=> GeoTrust Global CA [self-signed] [SHA1-RSA]
```

### CODE REVIEW

**Comment by csstaub** [comment]
Thinking that we should probably just wrap at 60 all the time. Thoughts? Checking the terminal width seems a bit overkill.

**Comment by mcpherrinm** [comment]
I think hardcoded wrapping at 60 would be fine, but the terminal width wrapping seems a little nicer.

**Comment by csstaub** [comment]
True, although anything below 60 is too little to be readable (and other parts of the output are 60 chars anyway) and above 80 becomes hard to read also. So the terminal-width adjustment in that range doesn't provide much value I think.

**Comment by mcpherrinm** [comment]
Yeah, but below 60 and the terminal will wrap it, so then you've got double wrapping.  It probably doesn't matter, though.

**Pull request merged**
